### PR TITLE
Added scraping function for fetching user details through coding ninjas platform

### LINKED ISSUE #23: Route for coding-ninjas profile
I would like to add Scraping function to scrape the coding ninjas profile data

### PR DESCRIPTION
**Pull request by GbCderr14**
Now 
<b>_/coding_ninjas/:username_</b>
 will give the details of the user's profile from coding ninjas platform..
for eg. 
image

fixes #23

### CODE REVIEW

**Comment by GbCderr14** [comment]
@Yash-Parsana have a look on it please

**Comment by Yash-Parsana** [comment]
@GbCderr14 great work, it looks good but one think is, it has very high latency around 10X as compare to other apis so try to improve that.

Some tips :
- There are so many await statements you can use Promise.all for independent statements.
- I think waitUntil: 'networkidle2' might taking more time so try to improve it.
- You may follow same module and logic that used to scrap other platform like code chef or at coder.

**Comment by GbCderr14** [comment]
@Yash-Parsana i tried with existing modules but those were not able to fetch the data may be due to high security measures applied by coding ninjas using normal fetch function was just fetching the scripts of the page and not the html so using pupeeteer was the best option for this situation.

**Comment by GbCderr14** [comment]
please check it now modified it.. @Yash-Parsana

**Pull request closed without merging**
